import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AstroIntegration } from 'astro';

/**
 * Writes dist/_headers — the file Cloudflare (Workers static assets or Pages)
 * reads to attach HTTP headers — after every build.
 *
 * The Content-Security-Policy is derived from the pages that were actually
 * built, so it can be strict without being maintained by hand:
 *  - inline <script> and <style> blocks are allowed by their exact sha256 hash
 *    (no 'unsafe-inline'); JSON-LD blocks are data, not code, and need none;
 *  - frame-src lists only the origins of the live demos (`data-demo-src`);
 *  - form-action lists only the origins forms actually post to.
 * Add a demo or a form and the policy follows on the next build.
 */

const INLINE_SCRIPT = /<script\b([^>]*)>([\s\S]*?)<\/script>/g;
const INLINE_STYLE = /<style\b[^>]*>([\s\S]*?)<\/style>/g;
const DEMO_SRC = /\bdata-demo-src="([^"]+)"/g;
const FORM_ACTION = /<form\b[^>]*\baction="([^"]+)"/g;

const sha256 = (text: string) => `'sha256-${createHash('sha256').update(text, 'utf8').digest('base64')}'`;

const decode = (value: string) =>
  value.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>');

function originOf(url: string): string | undefined {
  try {
    const { origin, protocol } = new URL(decode(url));
    return protocol === 'https:' ? origin : undefined;
  } catch {
    return undefined; // relative URL — covered by 'self'
  }
}

/** The full _headers file for a set of built HTML pages. */
export function buildHeaders(pages: string[]): string {
  const scripts = new Set<string>();
  const styles = new Set<string>();
  const frames = new Set<string>();
  const forms = new Set<string>();

  for (const html of pages) {
    for (const [, attrs = '', body = ''] of html.matchAll(INLINE_SCRIPT)) {
      if (/\bsrc=/.test(attrs) || /type="application\/(ld\+)?json"/.test(attrs)) continue;
      if (body.trim()) scripts.add(sha256(body));
    }
    for (const [, body = ''] of html.matchAll(INLINE_STYLE)) {
      if (body.trim()) styles.add(sha256(body));
    }
    for (const [, src = ''] of html.matchAll(DEMO_SRC)) {
      const origin = originOf(src);
      if (origin) frames.add(origin);
    }
    for (const [, action = ''] of html.matchAll(FORM_ACTION)) {
      const origin = originOf(action);
      if (origin) forms.add(origin);
    }
  }

  const sorted = (set: Set<string>) => [...set].sort();
  const csp = [
    "default-src 'self'",
    ["script-src 'self'", ...sorted(scripts)].join(' '),
    ["style-src 'self'", ...sorted(styles)].join(' '),
    "img-src 'self' data:",
    "media-src 'self'",
    "font-src 'self'",
    "connect-src 'self'",
    frames.size > 0 ? `frame-src ${sorted(frames).join(' ')}` : "frame-src 'none'",
    ["form-action 'self'", ...sorted(forms)].join(' '),
    "object-src 'none'",
    "base-uri 'self'",
    "frame-ancestors 'none'",
    'upgrade-insecure-requests',
  ].join('; ');

  return [
    '# Generated by src/integrations/security-headers.ts on every build — do not edit.',
    '/*',
    `  Content-Security-Policy: ${csp}`,
    '  X-Content-Type-Options: nosniff',
    '  X-Frame-Options: DENY',
    '  Referrer-Policy: strict-origin-when-cross-origin',
    '  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()',
    '  Cross-Origin-Opener-Policy: same-origin',
    '',
    '# Hashed file names: safe to cache forever.',
    '/_astro/*',
    '  Cache-Control: public, max-age=31536000, immutable',
    '',
    '/media/*',
    '  Cache-Control: public, max-age=604800',
    '',
  ].join('\n');
}

async function htmlFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true, recursive: true });
  return entries.filter((e) => e.isFile() && e.name.endsWith('.html')).map((e) => join(e.parentPath, e.name));
}

export default function securityHeaders(): AstroIntegration {
  return {
    name: 'security-headers',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const root = fileURLToPath(dir);
        const pages = await Promise.all((await htmlFiles(root)).map((file) => readFile(file, 'utf8')));
        await writeFile(join(root, '_headers'), buildHeaders(pages));
        logger.info(`wrote _headers for ${pages.length} pages`);
      },
    },
  };
}
